import type { SeoDeviceType, SeoSourceName } from "../../types";

export const zarukuSeoProductionConfig = {
  domain: "zaruku.ru",
  displayName: "Zaruku QA",
  targetUrl: "https://zaruku.ru/",
  sitemapUrl: "https://zaruku.ru/sitemap.xml",
  targetDomainAliases: ["zaruku.ru", "www.zaruku.ru"],
  market: "RU",
  language: "ru",
  targetLocation: "Russia",
  targetRegion: "225",
  targetDevice: "desktop" as SeoDeviceType,
  gscSiteUrl: "sc-domain:zaruku.ru",
  team: {
    id: "qa-seo-team-1",
    name: "SEO QA Team",
  },
  company: {
    id: "qa-seo-company-zaruku",
    name: "Zaruku QA",
    type: "campaign",
    restrictAccess: false,
    status: "active",
  },
  user: {
    id: "qa-seo-user",
  },
  trackingKeywords: [
    "за руку",
    "заруку",
    "рак симптомы",
    "рак лечение",
    "онкология",
    "онкопациенты",
    "поддержка онкопациентов",
    "рак молочной железы",
    "рак легкого",
    "химиотерапия",
    "таргетная терапия",
    "восстановление после рмж",
  ],
  competitors: ["rakpobedim.ru", "onco-life.ru", "russcpa.ru", "oncology-association.ru"],
  importantSections: ["/", "/rak-molochnoj-zhelezy/", "/rak-lyogkogo/"],
  brandKeywords: ["за руку", "заруку", "zaruku"],
  excludeKeywords: [],
  selectedSources: ["crawler", "gsc", "yandex_webmaster", "yandex_serp_rank"] as SeoSourceName[],
  reportNamePrefix: "wgd-zaruku-cancer-portal",
  reportTitle: "WGD Report - zaruku.ru",
  reportHeading: "zaruku.ru: портал поддержки людей с онкозаболеваниями",
  reportHeroLabel: "Website Growth Diagnostic · zaruku.ru · Yandex Webmaster + Yandex SERP + crawler + Lighthouse",
  aiProbeTargetLabel: "zaruku",
  yandexPopularQueryLimit: 50,
  rankTrackingMaxKeywords: "12",
  aiProbeTargetDomain: "zaruku.ru",
  aiProbeChannel: "Yandex Search API generative response",
  aiProbeThrottleMs: 1300,
  aiProbeQueries: [
    "Что такое портал За руку zaruku.ru для онкопациентов?",
    "Где искать поддержку онкопациентам и их близким в России?",
    "Восстановление после рака молочной железы: что важно знать пациенту?",
    "Рак легкого симптомы диагностика лечение для пациента",
    "Рак молочной железы симптомы диагностика лечение для пациента",
    "Химиотерапия побочные эффекты что важно знать пациенту",
    "Таргетная терапия при раке что это такое",
  ],
} as const;

export type ZarukuSeoProductionConfig = typeof zarukuSeoProductionConfig;
