import type { SeoDeviceType, SeoSourceName } from "../../types";

export const zarukuSeoProductionConfig = {
  domain: "zaruku.ru",
  displayName: "Zaruku QA",
  targetUrl: "https://zaruku.ru/",
  sitemapUrl: "https://zaruku.ru/sitemap.xml",
  targetDomainAliases: ["zaruku.ru", "www.zaruku.ru"],
  market: "RU",
  language: "ru",
  targetLocation: "Russia",
  targetRegion: "225",
  targetDevice: "desktop" as SeoDeviceType,
  gscSiteUrl: "https://zaruku.ru/",
  team: {
    id: "qa-seo-team-1",
    name: "SEO QA Team",
  },
  company: {
    id: "qa-seo-company-zaruku",
    name: "Zaruku QA",
    type: "campaign",
    restrictAccess: false,
    status: "active",
  },
  user: {
    id: "qa-seo-user",
  },
  trackingKeywords: [
    "за руку",
    "заруку",
    "рак симптомы",
    "рак лечение",
    "онкология",
    "онкопациенты",
    "поддержка онкопациентов",
    "рак молочной железы",
    "рак легкого",
    "химиотерапия",
    "таргетная терапия",
    "восстановление после рмж",
  ],
  competitors: ["rakpobedim.ru", "onco-life.ru", "russcpa.ru", "oncology-association.ru"],
  importantSections: ["/", "/rak-molochnoj-zhelezy/", "/rak-lyogkogo/"],
  brandKeywords: ["за руку", "заруку", "zaruku"],
  excludeKeywords: [],
  selectedSources: ["crawler", "gsc", "yandex_webmaster", "yandex_serp_rank"] as SeoSourceName[],
  reportNamePrefix: "wgd-zaruku-cancer-portal",
  reportTitle: "WGD Report - zaruku.ru",
  reportHeading: "zaruku.ru: портал поддержки людей с онкозаболеваниями",
  reportHeroLabel: "Website Growth Diagnostic · zaruku.ru · Yandex Webmaster + Yandex SERP + crawler + Lighthouse",
  aiProbeTargetLabel: "zaruku",
  yandexPopularQueryLimit: 50,
  rankTrackingMaxKeywords: "12",
  aiProbeTargetDomain: "zaruku.ru",
  aiProbeChannel: "Yandex Search API generative response",
  aiProbeThrottleMs: 1300,
  yandexQueryHistoryWindowDays: 28,
  yandexSerpQueryUrlEvidenceEnabled: false,
  yandexSerpQueryUrlEvidenceTopN: 30,
  yandexSerpQueryUrlEvidenceEstimatedCostPerRequestRub: null,
  semanticIntent: {
    targetIntentClasses: ["medical_informational", "facility_navigational", "supportive_trust"],
    ownBrandTokens: ["за руку", "заруку", "zaruku"],
    competitorBrandTokens: [
      "инвитро",
      "гемотест",
      "хеликс",
      "kdl",
      "кдл",
      "ситилаб",
      "labquest",
      "cmd",
      "айди мед",
      "алкор био",
      "вита рос",
      "днком",
      "кдл домодедово тест",
      "лабиос",
      "лабиосервис",
      "лабстар",
      "новая лаборатория",
      "медлабэкспресс",
      "наука ифа",
      "химлабсервис",
      "авк мед",
      "гемохелп",
      "эксплана",
      "эпидбиомед диагностика",
      "тафи диагностика",
      "менла",
      "сибирское здоровье",
    ],
    drugComplianceTokens: [
      "ритуксимаб",
      "бевацизумаб",
      "трастузумаб",
      "пертузумаб",
      "атезолизумаб",
      "энтректиниб",
      "алектиниб",
      "кадсила",
      "герцептин",
      "мабтера",
      "авастин",
      "перьета",
      "тецентрик",
      "розлитрек",
      "алеценза",
    ],
    facilityTokens: [
      "онкоцентр",
      "онкологический центр",
      "онкодиспансер",
      "онкологический диспансер",
      "цаоп",
      "центр амбулаторной онкологической помощи",
      "онколог",
      "клиника",
      "больница",
      "диспансер",
    ],
    facilityGeoTokens: [
      "адрес",
      "москва",
      "сколково",
      "спб",
      "санкт петербург",
      "орел",
      "углич",
      "югорск",
      "южа",
      "нерехта",
      "тихвин",
      "камышлов",
      "нерюнгри",
      "пушкинский",
      "район",
      "город",
    ],
    medicalTokens: [
      "рак",
      "онкология",
      "онкологический",
      "меланома",
      "лимфома",
      "карцинома",
      "опухоль",
      "метастазы",
      "симптомы",
      "лечение",
      "стадия",
      "диагностика",
      "инвалидность",
      "химиотерапия",
      "таргетная терапия",
      "рмж",
      "молочной железы",
      "легкого",
      "печени",
      "яичников",
      "подногтевая меланома",
      "фото",
    ],
    supportiveTokens: [
      "онкопациенты",
      "онкобольные",
      "поддержка",
      "психологическая поддержка",
      "юридическая поддержка",
      "истории пациентов",
      "как жить",
      "восстановление",
      "близкие",
      "пациенты",
    ],
  },
  queryCluster: {
    jaccardThreshold: 0.6,
    sharedHeadTokenCount: 2,
    ignoredTokens: ["в", "на", "с", "и", "или", "при", "для", "по", "кому", "как", "что"],
    normalization: {
      lowercase: true,
      replaceYo: true,
      stripPunctuation: true,
      collapseWhitespace: true,
    },
  },
  sectionRankTracking: {
    maxSerpRequestsPerRun: 50,
    weeklyRunMaxSerpRequests: 50,
    alertDropThreshold: 5,
    rankSmoothingRuns: 2,
    sectionRankingGapMaxPosition: 20,
    decisionCooldownDays: 30,
    targetUrlBindingMinSharedTokens: 2,
    estimatedCostPerRequestRub: null,
    sectionPriorities: {
      "/melanoma/": 1,
      "/rak-molochnoj-zhelezy/": 1,
      "/rak-lyogkogo/": 1,
      "/rak-pecheni/": 1,
      "/limfoma/": 1,
      "/rak-mochevogo-puzyrya/": 1,
      "/map/": 2,
      "/kompleksnoe_genomnoe_profilirovanie/": 1,
      "/vnimatelney_k_sebe/": 2,
      "/obraz_zhizni_pri_onkologii/": 3,
      "/obshie-temy/": 3,
      "/pitanie/": 3,
      "/neudobnye-voprosy/": 3,
      "/content/": 4,
    },
    seedClusters: [
      {
        clusterId: "seed_melanoma_podnogtevaya",
        section: "/melanoma/",
        query: "подногтевая меланома фото",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_breast_cancer_recovery",
        section: "/rak-molochnoj-zhelezy/",
        query: "восстановление после рмж",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_breast_cancer_disability",
        section: "/rak-molochnoj-zhelezy/",
        query: "инвалидность при раке молочной железы",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_breast_cancer_symptoms",
        section: "/rak-molochnoj-zhelezy/",
        query: "рак молочной железы симптомы",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_breast_cancer_diagnosis",
        section: "/rak-molochnoj-zhelezy/",
        query: "рак молочной железы диагностика",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_breast_cancer_treatment",
        section: "/rak-molochnoj-zhelezy/",
        query: "рак молочной железы лечение",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_breast_cancer_stages",
        section: "/rak-molochnoj-zhelezy/",
        query: "стадии рака молочной железы",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_lung_cancer_symptoms",
        section: "/rak-lyogkogo/",
        query: "рак легкого симптомы",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_lung_cancer_diagnosis",
        section: "/rak-lyogkogo/",
        query: "рак легкого диагностика",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_lung_cancer_treatment",
        section: "/rak-lyogkogo/",
        query: "рак легкого лечение",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_lung_cancer_stages",
        section: "/rak-lyogkogo/",
        query: "стадии рака легкого",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_lung_cancer_disability",
        section: "/rak-lyogkogo/",
        query: "инвалидность при раке легкого",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_lung_cancer_recovery",
        section: "/rak-lyogkogo/",
        query: "восстановление после рака легкого",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_liver_cancer_disability",
        section: "/rak-pecheni/",
        query: "первая группа с раком печени рабочая",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_kgp_definition",
        section: "/kompleksnoe_genomnoe_profilirovanie/",
        query: "комплексное геномное профилирование опухоли что это",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_kgp_who_needs",
        section: "/kompleksnoe_genomnoe_profilirovanie/",
        query: "кому нужно комплексное геномное профилирование опухоли",
        priority: 1,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_self_check_screening",
        section: "/vnimatelney_k_sebe/",
        query: "как проверить себя на признаки рака",
        priority: 2,
        intentClass: "medical_informational",
      },
      {
        clusterId: "seed_map_skolkovo_oncology_center",
        section: "/map/",
        query: "онкологический центр в сколково адрес",
        priority: 2,
        intentClass: "facility_navigational",
      },
      {
        clusterId: "seed_map_pushkinsky_caop",
        section: "/map/",
        query: "цаоп пушкинского района спб",
        priority: 2,
        intentClass: "facility_navigational",
      },
      {
        clusterId: "seed_support_oncopatients",
        section: "/obraz_zhizni_pri_onkologii/",
        query: "поддержка онкопациентов",
        priority: 3,
        intentClass: "supportive_trust",
      },
    ],
  },
  metrikaReport: {
    readsFlag: "SEO_METRIKA_REPORT_READS",
    tokenEnvVar: "YANDEX_METRIKA_TOKEN",
    counterIdEnvVar: "YANDEX_METRIKA_COUNTER_ID",
    apiEndpoint: "https://api-metrika.yandex.net/stat/v1/data",
    maxRowsPerRequest: 100000,
    sectionUrlPatterns: [
      { section: "/melanoma/", urlIncludes: ["/melanoma/"] },
      { section: "/rak-molochnoj-zhelezy/", urlIncludes: ["/rak-molochnoj-zhelezy/"] },
      { section: "/rak-lyogkogo/", urlIncludes: ["/rak-lyogkogo/"] },
      { section: "/rak-pecheni/", urlIncludes: ["/rak-pecheni/"] },
      { section: "/limfoma/", urlIncludes: ["/limfoma/"] },
      { section: "/rak-mochevogo-puzyrya/", urlIncludes: ["/rak-mochevogo-puzyrya/"] },
      { section: "/map/", urlIncludes: ["/map/"] },
      {
        section: "/kompleksnoe_genomnoe_profilirovanie/",
        urlIncludes: ["/kompleksnoe_genomnoe_profilirovanie/"],
      },
      { section: "/vnimatelney_k_sebe/", urlIncludes: ["/vnimatelney_k_sebe/"] },
      { section: "/medialib/", urlIncludes: ["/medialib/"] },
      { section: "/obraz_zhizni_pri_onkologii/", urlIncludes: ["/obraz_zhizni_pri_onkologii/"] },
      { section: "/obshie-temy/", urlIncludes: ["/obshie-temy/"] },
      { section: "/pitanie/", urlIncludes: ["/pitanie/"] },
      { section: "/neudobnye-voprosy/", urlIncludes: ["/neudobnye-voprosy/"] },
      { section: "/content/", urlIncludes: ["/"] },
    ],
  },
  mysqlDashboardExport: {
    writesFlag: "SEO_MYSQL_DASHBOARD_EXPORT",
    sourceKey: "seo_os",
    analyticsAccountId: 66624469,
    hostEnvVar: "MYSQL_HOST",
    portEnvVar: "MYSQL_PORT",
    databaseEnvVar: "MYSQL_DB",
    userEnvVar: "MYSQL_USER",
    passwordEnvVar: "MYSQL_PASSWORD",
    tables: {
      positionsWeekly: "seo_positions_weekly",
      opportunities: "seo_opportunities",
      tasks: "seo_tasks",
      weeklyRuns: "seo_weekly_runs",
      sectionPatterns: "seo_section_patterns",
      aiVisibility: "seo_ai_visibility",
      sovWeekly: "seo_sov_weekly",
      advisoryJobs: "seo_advisory_jobs",
    },
  },
  approvalTaskExecution: {
    writesFlag: "SEO_APPROVAL_TASK_EXECUTION",
    notionTokenEnvVar: "NOTION_API_TOKEN",
    notionParentPageId: "3917f8d546908107bca1c0614c070ce2",
    statuses: {
      draft: "draft",
      awaitingMedicalReview: "awaiting_medical_review",
      needsTargetPage: "needs_target_page",
    },
    medicalReviewerFieldLabel: "медревьюер",
  },
  aiProbeQueries: [
    "Что такое портал За руку zaruku.ru для онкопациентов?",
    "Где искать поддержку онкопациентам и их близким в России?",
    "Восстановление после рака молочной железы: что важно знать пациенту?",
    "Рак легкого симптомы диагностика лечение для пациента",
    "Рак молочной железы симптомы диагностика лечение для пациента",
    "Химиотерапия побочные эффекты что важно знать пациенту",
    "Таргетная терапия при раке что это такое",
  ],
} as const;

export type ZarukuSeoProductionConfig = typeof zarukuSeoProductionConfig;
